trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'

- script: java -jar saker.build.jar -bd build -trace pwd://build/build_test.trace test
  displayName: 'Test'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish test trace'
  inputs:
    pathtoPublish: build/build_test.trace
    artifactName: test_trace

- script: java -jar saker.build.jar -bd build -trace pwd://build/build_export.trace export
  displayName: 'Export'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish export trace'
  inputs:
    pathtoPublish: build/build_export.trace
    artifactName: export_trace

- script: cat hs_err*.log 2>/dev/null || echo "No hs_err files."
  condition: or( eq( variables['Agent.OS'], 'Linux' ), eq( variables['Agent.OS'], 'Darwin' ) )
  displayName: 'Display JVM crash logs (Linux)'
- script: type hs_err*.log 2>nul || exit 0
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Display JVM crash logs (Win)'
