trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # set the -e so the bash script exists if a command fails
    set -e
    curl https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
    java -jar saker.build.jar -bd build test
    java -jar saker.build.jar -bd build export
  displayName: 'Export library JAR'
